### ISSUE TITLE
agent metrics should expand all labels

### ISSUE THREAD

**Issue by leisurelyrcxf** [HunanTV/eru-agent#101]
In cadviosr, when your container has labels {"label1"=x,"label"=y,"label3"=z}, the metric should look like 

{container_label_label1="x",container_label_label2="y",container_label_label3="z"}

currently is {label="label1=x,label2=y,label3=z"} which is not a standard prometheus grammar thus impossible to match container labels.

**Comment by CMGS** [comment]
it's a wrong project
