### ISSUE TITLE
编译出错，是不是libcontainer版本的问题?

### ISSUE THREAD

**Issue by ahjdzx** [HunanTV/eru-agent#5]
``` bash
metrics/stats_linux.go:28: cannot use &c (type *cgroups.Cgroup) as type map[string]string in argument to fs.GetStats
```

**Comment by CMGS** [comment]
恩？你的 docker 版本是多少

**Comment by tonicmuroq** [comment]
Mine is `3f35b26b8b2dcd` and all is well, did you run `go get` first? Or maybe you can update the repository manually.

**Comment by ahjdzx** [comment]
@CMGS  docker是1.5.0

**Comment by ahjdzx** [comment]
@tonicbupt Where I can see `3f35b26b8b2dcd`?

**Comment by tonicmuroq** [comment]
@ahjdzx in you `GOPATH`, for example mine is `~/.go`, so just find `~/.go/src/github.com/docker/libcontainer`, and then see its git revision...  I guess it may not be the newest, you can have a try

**Comment by CMGS** [comment]
@ahjdzx libcontainer 修改了幺蛾子的结构体……我已经修正了。目前这个是和 influxdb 0.9 兼容的，0.8.8 他们弃疗了我们也就没做支持了
